version: '3.8'

services:
  web:
    image: php:8.1-apache
    ports:
      - "8000:80"
    volumes:
      - ./public_html:/var/www/html
      - ./apache-config.conf:/etc/apache2/sites-available/000-default.conf
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dune_tracker
      MYSQL_USER: dune_user
      MYSQL_PASSWORD: dune_pass
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d

volumes:
  mysql_data: